language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
before_install:
  - npm i mocha -g
  - npm i -g karma-cli
install:
  - npm install
before_script:
  - npm run build
branches:
  only:
  - master